name: CD/CI

on:
  push:
jobs:
  commit-stage-workflow:
    name: Commit Stage
    uses: zerai/oe-module-demo-farm-add-ons/.github/workflows/commit-stage.yaml@master
    with:
      triggering-sha: "${{ github.sha }}"
